package models

type ShipMountSymbol string

const (
	MOUNT_GAS_SIPHON_I       ShipMountSymbol = "MOUNT_GAS_SIPHON_I"
	MOUNT_GAS_SIPHON_II      ShipMountSymbol = "MOUNT_GAS_SIPHON_II"
	MOUNT_GAS_SIPHON_III     ShipMountSymbol = "MOUNT_GAS_SIPHON_III"
	MOUNT_SURVEYOR_I         ShipMountSymbol = "MOUNT_SURVEYOR_I"
	MOUNT_SURVEYOR_II        ShipMountSymbol = "MOUNT_SURVEYOR_II"
	MOUNT_SURVEYOR_III       ShipMountSymbol = "MOUNT_SURVEYOR_III"
	MOUNT_SENSOR_ARRAY_I     ShipMountSymbol = "MOUNT_SENSOR_ARRAY_I"
	MOUNT_SENSOR_ARRAY_II    ShipMountSymbol = "MOUNT_SENSOR_ARRAY_II"
	MOUNT_SENSOR_ARRAY_III   ShipMountSymbol = "MOUNT_SENSOR_ARRAY_III"
	MOUNT_MINING_LASER_I     ShipMountSymbol = "MOUNT_MINING_LASER_I"
	MOUNT_MINING_LASER_II    ShipMountSymbol = "MOUNT_MINING_LASER_II"
	MOUNT_MINING_LASER_III   ShipMountSymbol = "MOUNT_MINING_LASER_III"
	MOUNT_LASER_CANNON_I     ShipMountSymbol = "MOUNT_LASER_CANNON_I"
	MOUNT_MISSILE_LAUNCHER_I ShipMountSymbol = "MOUNT_MISSILE_LAUNCHER_I"
	MOUNT_TURRET_I           ShipMountSymbol = "MOUNT_TURRET_I"
)
