package models

type ShipType string

const (
	SHIP_PROBE              ShipType = "SHIP_PROBE"
	SHIP_MINING_DRONE       ShipType = "SHIP_MINING_DRONE"
	SHIP_INTERCEPTOR        ShipType = "SHIP_INTERCEPTOR"
	SHIP_LIGHT_HAULER       ShipType = "SHIP_LIGHT_HAULER"
	SHIP_COMMAND_FRIGATE    ShipType = "SHIP_COMMAND_FRIGATE"
	SHIP_EXPLORER           ShipType = "SHIP_EXPLORER"
	SHIP_HEAVY_FREIGHTER    ShipType = "SHIP_HEAVY_FREIGHTER"
	SHIP_LIGHT_SHUTTLE      ShipType = "SHIP_LIGHT_SHUTTLE"
	SHIP_ORE_HOUND          ShipType = "SHIP_ORE_HOUND"
	SHIP_REFINING_FREIGHTER ShipType = "SHIP_REFINING_FREIGHTER"
)
