package models

type SystemType string

const (
	SYSTEMTYPE_NEUTRON_STAR SystemType = "NEUTRON_STAR"
	SYSTEMTYPE_RED_STAR     SystemType = "RED_STAR"
	SYSTEMTYPE_ORANGE_STAR  SystemType = "ORANGE_STAR"
	SYSTEMTYPE_BLUE_STAR    SystemType = "BLUE_STAR"
	SYSTEMTYPE_YOUNG_STAR   SystemType = "YOUNG_STAR"
	SYSTEMTYPE_WHITE_DWARF  SystemType = "WHITE_DWARF"
	SYSTEMTYPE_BLACK_HOLE   SystemType = "BLACK_HOLE"
	SYSTEMTYPE_HYPERGIANT   SystemType = "HYPERGIANT"
	SYSTEMTYPE_NEBULA       SystemType = "NEBULA"
	SYSTEMTYPE_UNSTABLE     SystemType = "UNSTABLE"
)
