package models

type WaypointTraitSymbol string

const (
	WP_TRAIT_UNCHARTED               WaypointTraitSymbol = "UNCHARTED"
	WP_TRAIT_MARKETPLACE             WaypointTraitSymbol = "MARKETPLACE"
	WP_TRAIT_SHIPYARD                WaypointTraitSymbol = "SHIPYARD"
	WP_TRAIT_OUTPOST                 WaypointTraitSymbol = "OUTPOST"
	WP_TRAIT_SCATTERED_SETTLEMENTS   WaypointTraitSymbol = "SCATTERED_SETTLEMENTS"
	WP_TRAIT_SPRAWLING_CITIES        WaypointTraitSymbol = "SPRAWLING_CITIES"
	WP_TRAIT_MEGA_STRUCTURES         WaypointTraitSymbol = "MEGA_STRUCTURES"
	WP_TRAIT_OVERCROWDED             WaypointTraitSymbol = "OVERCROWDED"
	WP_TRAIT_HIGH_TECH               WaypointTraitSymbol = "HIGH_TECH"
	WP_TRAIT_CORRUPT                 WaypointTraitSymbol = "CORRUPT"
	WP_TRAIT_BUREAUCRATIC            WaypointTraitSymbol = "BUREAUCRATIC"
	WP_TRAIT_TRADING_HUB             WaypointTraitSymbol = "TRADING_HUB"
	WP_TRAIT_INDUSTRIAL              WaypointTraitSymbol = "INDUSTRIAL"
	WP_TRAIT_BLACK_MARKET            WaypointTraitSymbol = "BLACK_MARKET"
	WP_TRAIT_RESEARCH_FACILITY       WaypointTraitSymbol = "RESEARCH_FACILITY"
	WP_TRAIT_MILITARY_BASE           WaypointTraitSymbol = "MILITARY_BASE"
	WP_TRAIT_SURVEILLANCE_OUTPOST    WaypointTraitSymbol = "SURVEILLANCE_OUTPOST"
	WP_TRAIT_EXPLORATION_OUTPOST     WaypointTraitSymbol = "EXPLORATION_OUTPOST"
	WP_TRAIT_MINERAL_DEPOSITS        WaypointTraitSymbol = "MINERAL_DEPOSITS"
	WP_TRAIT_COMMON_METAL_DEPOSITS   WaypointTraitSymbol = "COMMON_METAL_DEPOSITS"
	WP_TRAIT_PRECIOUS_METAL_DEPOSITS WaypointTraitSymbol = "PRECIOUS_METAL_DEPOSITS"
	WP_TRAIT_RARE_METAL_DEPOSITS     WaypointTraitSymbol = "RARE_METAL_DEPOSITS"
	WP_TRAIT_METHANE_POOLS           WaypointTraitSymbol = "METHANE_POOLS"
	WP_TRAIT_ICE_CRYSTALS            WaypointTraitSymbol = "ICE_CRYSTALS"
	WP_TRAIT_EXPLOSIVE_GASES         WaypointTraitSymbol = "EXPLOSIVE_GASES"
	WP_TRAIT_STRONG_MAGNETOSPHERE    WaypointTraitSymbol = "STRONG_MAGNETOSPHERE"
	WP_TRAIT_VIBRANT_AURORAS         WaypointTraitSymbol = "VIBRANT_AURORAS"
	WP_TRAIT_SALT_FLATS              WaypointTraitSymbol = "SALT_FLATS"
	WP_TRAIT_CANYONS                 WaypointTraitSymbol = "CANYONS"
	WP_TRAIT_PERPETUAL_DAYLIGHT      WaypointTraitSymbol = "PERPETUAL_DAYLIGHT"
	WP_TRAIT_PERPETUAL_OVERCAST      WaypointTraitSymbol = "PERPETUAL_OVERCAST"
	WP_TRAIT_DRY_SEABEDS             WaypointTraitSymbol = "DRY_SEABEDS"
	WP_TRAIT_MAGMA_SEAS              WaypointTraitSymbol = "MAGMA_SEAS"
	WP_TRAIT_SUPERVOLCANOES          WaypointTraitSymbol = "SUPERVOLCANOES"
	WP_TRAIT_ASH_CLOUDS              WaypointTraitSymbol = "ASH_CLOUDS"
	WP_TRAIT_VAST_RUINS              WaypointTraitSymbol = "VAST_RUINS"
	WP_TRAIT_MUTATED_FLORA           WaypointTraitSymbol = "MUTATED_FLORA"
	WP_TRAIT_TERRAFORMED             WaypointTraitSymbol = "TERRAFORMED"
	WP_TRAIT_EXTREME_TEMPERATURES    WaypointTraitSymbol = "EXTREME_TEMPERATURES"
	WP_TRAIT_EXTREME_PRESSURE        WaypointTraitSymbol = "EXTREME_PRESSURE"
	WP_TRAIT_DIVERSE_LIFE            WaypointTraitSymbol = "DIVERSE_LIFE"
	WP_TRAIT_SCARCE_LIFE             WaypointTraitSymbol = "SCARCE_LIFE"
	WP_TRAIT_FOSSILS                 WaypointTraitSymbol = "FOSSILS"
	WP_TRAIT_WEAK_GRAVITY            WaypointTraitSymbol = "WEAK_GRAVITY"
	WP_TRAIT_STRONG_GRAVITY          WaypointTraitSymbol = "STRONG_GRAVITY"
	WP_TRAIT_CRUSHING_GRAVITY        WaypointTraitSymbol = "CRUSHING_GRAVITY"
	WP_TRAIT_TOXIC_ATMOSPHERE        WaypointTraitSymbol = "TOXIC_ATMOSPHERE"
	WP_TRAIT_CORROSIVE_ATMOSPHERE    WaypointTraitSymbol = "CORROSIVE_ATMOSPHERE"
	WP_TRAIT_BREATHABLE_ATMOSPHERE   WaypointTraitSymbol = "BREATHABLE_ATMOSPHERE"
	WP_TRAIT_JOVIAN                  WaypointTraitSymbol = "JOVIAN"
	WP_TRAIT_ROCKY                   WaypointTraitSymbol = "ROCKY"
	WP_TRAIT_VOLCANIC                WaypointTraitSymbol = "VOLCANIC"
	WP_TRAIT_FROZEN                  WaypointTraitSymbol = "FROZEN"
	WP_TRAIT_SWAMP                   WaypointTraitSymbol = "SWAMP"
	WP_TRAIT_BARREN                  WaypointTraitSymbol = "BARREN"
	WP_TRAIT_TEMPERATE               WaypointTraitSymbol = "TEMPERATE"
	WP_TRAIT_JUNGLE                  WaypointTraitSymbol = "JUNGLE"
	WP_TRAIT_OCEAN                   WaypointTraitSymbol = "OCEAN"
	WP_TRAIT_STRIPPED                WaypointTraitSymbol = "STRIPPED"
)
